### ISSUE TITLE
Modificaciones sobre hipervinculos

### ISSUE THREAD

**Issue by NicolasTrujillo** [matiexe/kaizen-react#6]
Buenas. Mati

Sobre estos 2, podras modificar el hipervinculo del CIT, cluster de impulso tecnológico por este: https://cit.org.ar/

Y remove el hipervinculo del Cluster Santa Cruz, dejalo sin link por favor

![image](https://github.com/matiexe/kaizen-react/assets/15672166/b3ecfa93-47ec-4354-b136-4c8da2d81068)

Avisame.
Gracias.
NIco

**Comment by matiexe** [comment]
modificaciones realizadas y puestas en produccion
